{:ok, _} = Application.ensure_all_started(:ex_machina)
ExUnit.configure(exclude: [pending: true], formatters: [JUnitFormatter, ExUnit.CLIFormatter])
Ecto.Adapters.SQL.Sandbox.mode(Rootbus.Repo, :manual)
ExUnit.start()
Faker.start()
